### ISSUE TITLE
Dobiss NXT v3.80 - toggles

### ISSUE THREAD

**Issue by WishMaster666** [kesteraernoudt/dobiss#202]
I upgraded my Dobiss NXT to version 3.80.

I get this image for 1-2 seconds when I click the toggle (turn on the light, the light does turn on):
![image](https://github.com/user-attachments/assets/48eb7ed1-0684-475b-a73c-7fb52c5459a3)

It then switches back to this image (but the light stays on):
![image](https://github.com/user-attachments/assets/8768bc27-ce6a-4541-a23b-d81935cb1ef0)

I cannot use the toggle to turn off the light in Home Assistant.
I guess the second line in the release notes has something to do with it?

> 3.80
>    Monitor consumers: select EV Charger
>    **NXT relay outputs: action types pulse follower and up/down**
>    Artsound: option to always ungroup before action
>    Zigbee (Azoula): integration of new device types
>    Upgrade: show what's new before installing
>    BETA testing: integration with Home Connect
>    BETA testing: integration with Daikin Onecta

**Comment by timvdsm** [comment]
I also have problems since the 3.80 update. 

Here is my log: 
```
Logger: dobissapi.dobissapi
Bron: /usr/local/lib/python3.12/site-packages/dobissapi/dobissapi.py:890
Eerst voorgekomen: 14:29:03 (118 gebeurtenissen)
Laatst gelogd: 14:48:37

Failed to connect, waiting a bit before retrying: ClientResponseError(RequestInfo(url=URL('ws://x.x.x.x/sockets/api'), method='GET', headers=<CIMultiDictProxy('Host': 'x.x.x.x', 'Authorization': 'Bearer x.x', 'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Key': 'xxxx==', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Python/3.12 aiohttp/3.10.8')>, real_url=URL('ws://x.x.x.x/sockets/api')), (), status=426, message='No Sec-WebSocket-Protocols requested supported', headers=<CIMultiDictProxy('Server': 'nginx/1.18.0', 'Date': 'Wed, 16 Oct 2024 12:47:57 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Upgrade': 'websocket', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Protocol': 'wamp', 'X-Powered-By': 'Ratchet/0.4.4')>)
Failed to connect, waiting a bit before retrying: 
....

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dobissapi/dobissapi.py", line 858, in listen_for_dobiss
    ws = await self._session.ws_connect(self._ws_url, headers=headers)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 933, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 789, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 426, message='No Sec-WebSocket-Protocols requested supported', url='ws://x.x.x.x/sockets/api'
```

**Comment by kesteraernoudt** [comment]
Unfortunately I moved out and don’t have direct access to the dobiss system anymore.It does look like the sending of commands still work, but the connection to the updates from dobiss next is failing. I’ll have a look and see if I can find what has changed - I may need some help to test things…On Oct 16, 2024, at 11:16 AM, timvdsm ***@***.***> wrote:﻿
I also have problems since the 3.80 update.
Here is my log:
Logger: dobissapi.dobissapi
Bron: /usr/local/lib/python3.12/site-packages/dobissapi/dobissapi.py:890
Eerst voorgekomen: 14:29:03 (118 gebeurtenissen)
Laatst gelogd: 14:48:37

Failed to connect, waiting a bit before retrying: ClientResponseError(RequestInfo(url=URL('ws://x.x.x.x/sockets/api'), method='GET', headers=<CIMultiDictProxy('Host': 'x.x.x.x', 'Authorization': 'Bearer x.x', 'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Key': 'xxxx==', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Python/3.12 aiohttp/3.10.8')>, real_url=URL('ws://x.x.x.x/sockets/api')), (), status=426, message='No Sec-WebSocket-Protocols requested supported', headers=<CIMultiDictProxy('Server': 'nginx/1.18.0', 'Date': 'Wed, 16 Oct 2024 12:47:57 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Upgrade': 'websocket', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Protocol': 'wamp', 'X-Powered-By': 'Ratchet/0.4.4')>)
Failed to connect, waiting a bit before retrying: 
....

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dobissapi/dobissapi.py", line 858, in listen_for_dobiss
    ws = await self._session.ws_connect(self._ws_url, headers=headers)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 933, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 789, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 426, message='No Sec-WebSocket-Protocols requested supported', url='ws://x.x.x.x/sockets/api'

**Comment by timvdsm** [comment]
> It does look like the sending of commands still work, but the connection to the updates from dobiss next is failing.
>
Indeed, for example: a light is off, when you toggle the entity in HA, the command activates the light in reality. However in HA the state stays "off". When you once click the light in HA nothing happens as in reality the light stays on. 

> I may need some help to test things…
> 
Sure no problem, with a lot's of pleasure ;-)

**Comment by kesteraernoudt** [comment]
I've uploaded a new dev version - there is an API change that required some changes in my code as well. As I can't test this, please let me know if you can try this out.

I did receive a note from the dobiss team that the first 3.8 version of the NXT server had a bug - just re-install the version now should fix that as well!

**Comment by WishMaster666** [comment]
re-install Dobiss NXT 3.80 didn't solve anything for me 😕
How do I try your dev version?

**Comment by NDon1093** [comment]
I am having a similar issue. I have a set of automations on Home Assistant based on the status of the system of Dobiss (for example certain lights that are on or off). These automations worked fine before version 3.8 of dobiss, yet stopped working now. I notice that I can still turn on or off lights from Home Assistant though, so the connection in general is working fine.

I want to stress that I am very happy with this addon, so many thanks to the developers of it!

**Comment by timvdsm** [comment]
> I've uploaded a new dev version - there is an API change that required some changes in my code as well. As I can't test this, please let me know if you can try this out.
> 
> I did receive a note from the dobiss team that the first 3.8 version of the NXT server had a bug - just re-install the version now should fix that as well!

Hi many thanks for the fast response as always :-)

I don't see a new dev version available on the dobiss hacs. Also on the dobiss github respository I don't see a new dev version available. However I see there is a new dev version available on the pydobiss github.  But I guess the dobiss hacs is linked to the dobiss repository? 

<img width="1406" alt="Scherm­afbeelding 2024-10-18 om 09 11 00" src="https://github.com/user-attachments/assets/68833e36-8e5b-453f-a2f0-a86d0f8aa40e">


<img width="875" alt="Scherm­afbeelding 2024-10-18 om 09 07 33" src="https://github.com/user-attachments/assets/00b12cc5-6b7c-43c3-a38a-839d8ef656f6">

**Comment by timvdsm** [comment]
In HA - HACS ... I am still only able to download  v1.8 or older. 
I guess that's the "master" respository? Any way to select the dev repository? Or should the dev build needs to made available in the master repo so it becomes visual in HA HACS?

**Comment by kesteraernoudt** [comment]
I see the dev version when I enable beta versions:

![image](https://github.com/user-attachments/assets/3f990396-0d03-4a74-94fd-651e65fbf434)

Is that not available for you?

**Comment by timvdsm** [comment]
Indeed, I remember the toggle in the previous HACS version. I am using HACS 2.0 now and I don't see or find the "show beta versions" toggle anymore ... but maybe that's because it's Friday :-)

<img width="893" alt="Scherm­afbeelding 2024-10-18 om 19 12 59" src="https://github.com/user-attachments/assets/5dd84d72-f62f-4ae3-b760-a69852a5344c">

I don't know if they changed something in HACS 2.0? 

I read here ... https://www.hacs.xyz/docs/publish/start/?h=versions#hacsjson
`Allow Home Assistant beta versions by appending b0. Without b0, only official releases will be allowed.`

But maybe I am totally wrong?

**Comment by kesteraernoudt** [comment]
Ow that's strange they removed that. I'll have a look if there is still a way to install a dev version...

**Comment by timvdsm** [comment]
Maybe a very stupid question: 

Are only the following lines of code changed in the custom component - manifest.json?
```
  "requirements": [
    "pydobiss==0.1.54",
    "xknx==0.9.4"
  ],
```
Can't I just hardcopy change it in the "config/custom_components/dobiss/manifest.json" file? 
and restart HA. So in total it looks like this ... 
```
{
  "domain": "dobiss",
  "name": "dobiss",
  "codeowners": [
    "@kesteraernoudt"
  ],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://www.home-assistant.io/integrations/dobiss",
  "homekit": {},
  "iot_class": "local_push",
  "issue_tracker": "https://github.com/kesteraernoudt/dobiss/issues",
  "requirements": [
    "pydobiss==0.1.54",
    "xknx==0.9.4"
  ],
  "ssdp": [],
  "version": "1.0.0",
  "zeroconf": []
}
```

**Comment by kesteraernoudt** [comment]
That's the only change indeed. But I think this is only used by HA when installing the integration, not when starting. It's worth a try tho

**Comment by timvdsm** [comment]
Nope that didn't do the trick 👎

**Comment by Eightball1990** [comment]
Hi kesteraernoud, 
first of all let me take the opportunity to thank you for writing this amazing integration! 

That being said, I have the same issue as everyone else after upgrading the NXT server to 3.80. 

Going further on what timvdsm tried;
If I would completely remove your custom integration and then perform the manual installation where your updated manifest.json file is included, I suppose it should work again, right? But would I still have all my automations or would they be gone once I remove your integration? Are there any other downsides to remove and readadd your custom integration? If not I am willing to try and report the result here.

**Comment by StijnVdd** [comment]
Hi,

I too would like to tank you for this integration!

I can confirm the code changes fixes the issue

Steps I took:
- redownload the latest version of the integration V1.8
- connected to the console of my HA docker container and updated the manifest to 0.1.54
- restarted HA
- checked the installed version of pydobiss and it was now updated to 0.1.54

**Comment by WishMaster666** [comment]
>     * redownload the latest version of the integration V1.8
>     * connected to the console of my HA docker container and updated the manifest to 0.1.54
>     * restarted HA
>     * checked the installed version of pydobiss and it was now updated to 0.1.54

I tried the same, no fix for me... How/where did you check the pydobiss version?

**Comment by StijnVdd** [comment]
I changed it in the manifest.json under /config/custom_components/dobiss

```
{
  "domain": "dobiss",
  "name": "dobiss",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/dobiss",
  "requirements": ["pydobiss==0.1.54", "xknx==0.9.4"],
  "ssdp": [],
  "zeroconf": [],
  "homekit": {},
  "dependencies": [],
  "version": "1.0.0",
  "issue_tracker": "https://github.com/kesteraernoudt/dobiss/issues",
  "codeowners": ["@kesteraernoudt"],
  "iot_class": "local_push"
}
```

**Comment by WishMaster666** [comment]
I did the same:
- redownload v1.8 of dobiss integration
- update manifest.json -->
   ![image](https://github.com/user-attachments/assets/1adccedd-dc9f-4985-b4cf-31754804d19e)
- restart Home Assistant
(manifest.json stays the same as in screenshot above after restart HA)

I've made a [short video](https://www.youtube.com/shorts/VF9do6mYkZc) of what happens:
- first click: light goes on, and toggle switches on for 1-2 seconds and then automatically goes to the 'off' state
- second click: nothing happens (light stays on)
- third + fourth click: when I click fast enough when the toggle is in the 'on' state, I can turn off the light

**Comment by NDon1093** [comment]
If I install the updated pydobiss package as described, my web-socket of Dobiss fails... Not sure why. I reinstalled the original 1.8 version of the HACS integration, and the web-socket started working again. Any clue why this could happen?

**Comment by timvdsm** [comment]
> If I install the updated pydobiss package as described, my web-socket of Dobiss fails... 

Well to be honest, I also got a failure of my web-socket on dobiss nxt a couple of days ago. I thought it had nothing to do with the testing as I was under the impression that the update of the dobiss integration was not done successfully. 

@StijnVdd yours is working perfectly now?

**Comment by WishMaster666** [comment]
> If I install the updated pydobiss package as described, my web-socket of Dobiss fails... Not sure why. I reinstalled the original 1.8 version of the HACS integration, and the web-socket started working again. Any clue why this could happen?

Same here... the dobiss icon kept spinning
![image](https://github.com/user-attachments/assets/a9d023ab-a54a-4a55-afc6-9c614bc55b00)
Re-installed the 1.8 version; dobiss is working again now (dobiss in HA still 'broken')

**Comment by WishMaster666** [comment]
Hmm, I'm running HA on a VM in ProxMox; not sure how/where I can recreate your steps.
Seems like a 1.9 version from Kester might do the trick then...

**Comment by WishMaster666** [comment]
> For those that ran into issues: can you check if you reinstall dobiss NXT and then restart, if it solves the problem?

Didn't solve it for me... (dobiss is running fine, Dobiss-HA is 'broken')

**Comment by kesteraernoudt** [comment]
Can you get to a console on you HA VM and run the pip freeze and potentially pip update pydobiss commands?

**Comment by kesteraernoudt** [comment]
Ok too bad. Thanks for testing. Does anyone else that is able to verify the version have any issues with it? If not I'll create a release

**Comment by DevIT-Germain** [comment]
> > If I install the updated pydobiss package as described, my web-socket of Dobiss fails... Not sure why. I reinstalled the original 1.8 version of the HACS integration, and the web-socket started working again. Any clue why this could happen?
> 
> Same here... the dobiss icon kept spinning ![image](https://private-user-images.githubusercontent.com/74816140/378183342-a9d023ab-a54a-4a55-afc6-9c614bc55b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDk4NDMsIm5iZiI6MTcyOTQ0OTU0MywicGF0aCI6Ii83NDgxNjE0MC8zNzgxODMzNDItYTlkMDIzYWItYTU0YS00YTU1LWFmYzYtOWM2MTRiYzU1YjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE4MzkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOWQxNTM5MGIzOWJkZTdlZDkwMjFjYzdjMmYxZjM4ZTM2N2I5ZjliMmQ0ZDE0N2ViZGJiYjA4ZjhhMjY5ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hX1RFGm8kMumfauAILDgPAGZeIEnww1C6J2Rj6GIKbU) Re-installed the 1.8 version; dobiss is working again now (dobiss in HA still 'broken')

I have the same problem

**Comment by timvdsm** [comment]
> Make sure to reinstall dobiss NXT v3.8 as well as they told me there was an issue with the websocket connection initially.

I firstly reinstalled dobiss nxt 3.80 using "Configuratie/Modules/NXT/Upgrade to 3.80". 
<img width="379" alt="Scherm­afbeelding 2024-10-20 om 21 54 29" src="https://github.com/user-attachments/assets/8f5011c5-f9f2-41fe-91fe-243a5930060a">
Then changed the code in the dobiss custom component en restarted HA. Afterwards indeed the web-sockets service of dobiss was stopped. If I remember correctly in the dobiss log itself there was a fatal error somewhere ... but I don't know the exact description anymore as I just saw in the day after. 

Anyone  who's web-sockets service stopped today, can check in their log the exact description (Configuratie/status/logs)?  Maybe that's helpfull @kesteraernoudt ?

**Comment by groovydc** [comment]
Good to know not to updat my dobiss :D i rarly use it by the way it's so slow

**Comment by kesteraernoudt** [comment]
I've published Release v1.9 - let me know if this fixes the websocket connection!

**Comment by Eightball1990** [comment]
> I've published Release v1.9 - let me know if this fixes the websocket connection!

It works! Thank you so much!

**Comment by NDon1093** [comment]
> I've published Release v1.9 - let me know if this fixes the websocket connection!

It doesn't for me unfortunately. If I install this version, my websocket stops working. Is there any other action I should take to resolve the issues?

**Comment by Eightball1990** [comment]
Maybe I should mention that my home assistant runs on a Home Assistant Yellow.
I have just (re)downloaded the v1.9 through HACS and did a restart of Home Assistant.
After reboot finished, the status of all my lights was displayed correctly again :)

**Comment by timvdsm** [comment]
Same for me with v1.9, web-sockets stops.
<img width="1124" alt="Scherm­afbeelding 2024-10-21 om 20 28 42" src="https://github.com/user-attachments/assets/2ef5ee37-5c07-4f15-9118-46c6b1b01aa7">


This is the log from dobiss itself ... 
<img width="1146" alt="Scherm­afbeelding 2024-10-21 om 20 30 11" src="https://github.com/user-attachments/assets/367c2ef2-b671-4842-991f-46b4dc1b569c">

@Eightball1990 did you do a reinstall of dobiss nxt 3.80 again? And if so, how did you do that exactly?

**Comment by NDon1093** [comment]
> > Same for me with v1.9, web-sockets stops. <img alt="Scherm­afbeelding 2024-10-21 om 20 28 42" width="1124" src="https://private-user-images.githubusercontent.com/14946020/378555521-2ef5ee37-5c07-4f15-9118-46c6b1b01aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzYwNDksIm5iZiI6MTcyOTUzNTc0OSwicGF0aCI6Ii8xNDk0NjAyMC8zNzg1NTU1MjEtMmVmNWVlMzctNWMwNy00ZjE1LTkxMTgtNDZjNmIxYjAxYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE4MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGU5ZjUwM2RjMmM4YWVmNDFjZWViNTcyYzdjNWE2NWYxYjg5YzYwZjNhN2Q4MzdiNGFjMzBlY2Y3ZWY1YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PxqUblbDTQpqa4JvHPxUbJzuSGpK9vdNe961Wymsq-4">
> > This is the log from dobiss itself ... <img alt="Scherm­afbeelding 2024-10-21 om 20 30 11" width="1146" src="https://private-user-images.githubusercontent.com/14946020/378555431-367c2ef2-b671-4842-991f-46b4dc1b569c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzYwNDksIm5iZiI6MTcyOTUzNTc0OSwicGF0aCI6Ii8xNDk0NjAyMC8zNzg1NTU0MzEtMzY3YzJlZjItYjY3MS00ODQyLTk5MWYtNDZiNGRjMWI1NjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE4MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZDQ1NDYyZTFhZjZmZjEyY2E2NGViMmExZTIxNTgxNTU0ZGMwNGRlNDQwMzIyYjNiZjQ0ODFlNGExMjI4M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3vlX9AOeLKTHVQK5octaCakm7a3-HB3Yg06Pk-niOlw">
> > @Eightball1990 did you do a reinstall of dobiss nxt 3.80 again? And if so, how did you do that exactly?
> 
> I did (prior to upgrading the Dobiss integration), just by clicking the 'upgrade to 3.80' button in the Dobiss Config, in the modules overview, again.

I have no idea why, but that did the trick! It is working again :-) Thank you all for the support!

**Comment by kesteraernoudt** [comment]
@timvdsm your issue seems to be with dobiss NXT itself? If you update it again using what @NDon1093 did, does that change anything? Maybe check if the websockets work before starting HA?

**Comment by DevIT-Germain** [comment]
I uninstalled Dobiss on HA and reinstalled it, but I’m still experiencing the same issue after connecting to Dobiss. The switches also seem to have the same bug.

**Comment by timvdsm** [comment]
> @timvdsm your issue seems to be with dobiss NXT itself? If you update it again using what @NDon1093 did, does that change anything? Maybe check if the websockets work before starting HA?

I can confirm everything is working now! Ahoi ahoi! 
- First downgraded the dobiss HA integration in hacs to 1.8. And checked if dobiss itself was running fine with the web-sockets service running. 
- Then I did a re-install of dobiss 3.80 in "Configuratie/Modules/NXT/Upgrade to 3.80" (strange as I already did that some days ago when it was mentioned in the thread here). And checked if the web-sockets service was still running. 
- Then upgrade of the dobiss hacs integration to v1.9
- Restart HA

Many thanks @kesteraernoudt and all of you once again!

**Comment by DevIT-Germain** [comment]
> > @timvdsm your issue seems to be with dobiss NXT itself? If you update it again using what @NDon1093 did, does that change anything? Maybe check if the websockets work before starting HA?
> 
> I can confirm everything is working now! Ahoi ahoi!
> 
> * First downgraded the dobiss HA integration in hacs to 1.8. And checked if dobiss itself was running fine with the web-sockets service running.
> * Then I did a re-install of dobiss 3.80 in "Configuratie/Modules/NXT/Upgrade to 3.80" (strange as I already did that some days ago when it was mentioned in the thread here). And checked if the web-sockets service was still running.
> * Then upgrade of the dobiss hacs integration to v1.9
> * Restart HA
> 
> Many thanks @kesteraernoudt and all of you once again!

THank you all, it works ;)

**Comment by WishMaster666** [comment]
>     * First downgraded the dobiss HA integration in hacs to 1.8. And checked if dobiss itself was running fine with the web-sockets service running.
>     * Then I did a re-install of dobiss 3.80 in "Configuratie/Modules/NXT/Upgrade to 3.80" (strange as I already did that some days ago when it was mentioned in the thread here). And checked if the web-sockets service was still running.
>     * Then upgrade of the dobiss hacs integration to v1.9
>     * Restart HA
This procedure also worked for me ! 🥳

**Comment by kesteraernoudt** [comment]
glad it seems to work for everyone now!

**Comment by bosjp** [comment]
many thanks !!!!
I also needed to reinstall 3.8 two times on NXT and after uninstall Dobiss on HA and reinstall but now everything is working again !
you are the best @kesteraernoudt ;-)

**Comment by jensMV** [comment]
i want to add that i was unable to load properly into dobiss webgui until i turned off my HA completely.
Disabling / removing the service was not sufficient.
Once that was done, the websockets service becomes available again and you can reinstall 3.80 from the modules menu.
